[package]
name = "andromeda-modules"
version = "0.1.0"
authors = ["Connor Barr <crnbarr@gmail.com>"]
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.0.0"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.3"
cw20 = "0.13.2"
cw-storage-plus = "0.13.2"
chrono = { path = "../chrono" }
thiserror = { version = "1.0.21" }
semver = "1"
ado-base = { path = "../ado-base" }

common = { path = "../common", version = "0.1.0" }

[dev-dependencies]
andromeda-testing = { version = "0.1.0", path = "../andromeda-testing" }

