[package]
name = "andromeda-ibc"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["stargate"] }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.3"
cw-storage-plus = "0.13.2"
cw20 = "0.13.2"
cw2 = "0.13.2"
cw-asset = "2.0.0"
cw-utils = "0.14.0"
thiserror = "1.0.32"
cw-controllers = "0.14.0"
semver = "1"


andromeda-ecosystem = { version = "0.1.0", path = "../../../packages/andromeda-ecosystem" }
common = { version = "0.1.0", path = "../../../packages/common" }
ado-base = { path = "../../../packages/ado-base", version = "0.1.0", features = ["instantiate"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
prost = "0.9.0"

andromeda-testing = { version = "0.1.0", path = "../../../packages/andromeda-testing" }